### ISSUE TITLE
Arguments in POST body?

### ISSUE THREAD

**Issue by Vultwo** [digitalocean/sample-functions-nodejs-qrcode#8]
Hi, all examples put the function arguments in the URL.
Is it possible to send a POST request containing the arguments?
I don't think it's safe to send sensitive information as a query.

**Comment by rabbah** [comment]
hi @Vultwo sorry for not responding sooner. Yes, you can send paramteers via POST, I hope you'd figured that out by now. The content-type must be application/json (or form data) and be a JSON object. The system will parse the body and provide all the properties (keys) in the object as first class arguments to your function. If you don't want the system to parse the body at all, that's also possible, by changing the `web: true` declaration in `project.yml` to `web: raw`.

Here are two examples of an echo function:
```
function main(args) { return { body: args } }
```

### POST JSON

```
curl -X POST -H "Content-Type: application/json" -d '{"key1":"value1", "key2":"value2"}' `doctl sls fn get echo --url`
```
```
{
  "__ow_headers": {... },
  "__ow_method": "post",
  "__ow_path": "",
  "key1": "value1",
  "key2": "value2"
}
```

#### POST form data
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "param1=value1&param2=value2"  `doctl sls fn get echo --url`
```
```
{
  "__ow_headers": {...},
  "__ow_method": "post",
  "__ow_path": "",
  "param1": "value1",
  "param2": "value2"
}
```

**Comment by Vultwo** [comment]
Hi, yeah I managed to figure it out. Thanks for the response anyway and sorry for not closing the issue earlier.
